//! [Problem 2](https://projecteuler.net/problem=2) Even Fibonacci numbers

//! Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//!
//! 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//!
//! By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

use num_seq::Fibonacci;

fn even_fibonacci_numbers(bound: u32) -> u32 {
    Fibonacci::<u32>::new()
        .take_while(|&f| f < bound)
        .filter(|&f| f & 1 == 0)
        .sum()
}

#[cfg(test)]
mod tests {

    #[test]
    fn test() {
        assert_eq!(super::even_fibonacci_numbers(90), 44);
    }
}
